### ISSUE TITLE
Doesn't support systemd-boot?

### ISSUE THREAD

**Issue by nordmagnus999** [DaVukovic/script.getedid#1]
I'm using Popos! (ubuntu 19.04 based) on x64, with intel and nvidia (optimus) on a laptop.
I wanted to use this script but sadly it seems it doesn't support systemd-boot (which i'm using, since it detect uefi is enabled)

`You neither have a extlinux.conf nor do you have a syslinux.cfg.
Dual boot systems aren't supported`
I'm just guessing the above because of this message.
Wish it could work as i need something like this.

**Comment by DaVukovic** [comment]
Lol, missed that for about 5 years :D 

To answer your question....feel free to fork and change it to match your need. This script was made for LibreELEC only. Hence I won't add support for any other OS.
